### ISSUE TITLE
Thanks for explaining the motivation

### ISSUE THREAD

**Issue by blentz100** [anishathalye/assets#1]
Great idea and the explanation helps me better understand how git and github works. Thank you Anish.

**Comment by Justintime50** [comment]
I agree, didn't have a great way to contact you so I'll jump on this and say thanks for the inspiration - [I'm going to do the same](https://github.com/Justintime50/assets) with my ~60 repos.

I also plan to use the `BFG Repo Cleaner` tool to clean out my old checked-in assets on each repo so that the history and sizes are nice and small.

**Comment by anishathalye** [comment]
Thanks for the kind words :)
